In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [3]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [6]:
import pandas as pd
df = pd.DataFrame(a1) 
df

,0
0,1
1,2
2,3


In [7]:
ones = np.ones([10, 2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
zeros = np.zeros([7, 2, 3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
a4 = np.arange(0, 100, 3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
a5 = np.random.randint(10, size=(7, 2))
a5

array([[9, 2],
       [4, 2],
       [6, 3],
       [8, 4],
       [7, 2],
       [3, 7],
       [7, 0]])

In [11]:
a6 = np.random.random((3, 5))
a6

array([[0.28623831, 0.63550703, 0.58897087, 0.49492171, 0.60104836],
       [0.03607844, 0.07132668, 0.67235696, 0.36090361, 0.33782772],
       [0.38361031, 0.43596626, 0.11260058, 0.53696265, 0.09804718]])

In [12]:
np.random.seed(42)
a7 = np.random.randint(10, size=(4, 6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
a8 = np.random.randint(10, size=(3, 7))
np.unique(a8)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [14]:
a8[0]

array([8, 0, 9, 2, 6, 3, 8])

In [15]:
a8[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [16]:
a8[:2, :2]

array([[8, 0],
       [2, 4]])

In [17]:
a9 = np.random.randint(10, size=(3, 5))
a10 = np.ones([3, 5])
a9, a10

(array([[4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7],
        [3, 1, 5, 5, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
a9 + a10

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [19]:
a11 = np.ones([5, 3])
a11

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a9 + a11

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
a12 = np.ones([3, 5])
a12

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
a9 - a12

array([[ 3.,  0.,  2.,  5.,  6.],
       [ 1., -1.,  2.,  0.,  6.],
       [ 2.,  0.,  4.,  4.,  8.]])

In [23]:
a9 * a12

array([[4., 1., 3., 6., 7.],
       [2., 0., 3., 1., 7.],
       [3., 1., 5., 5., 9.]])

In [24]:
a9 ** 2

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [25]:
np.square(a9)

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]])

In [26]:
np.mean(a9)

3.8

In [27]:
np.max(a9)

9

In [28]:
np.min(a9)

0

In [29]:
np.std(a9)

2.5612496949731396

In [30]:
np.var(a9)

6.5600000000000005

In [31]:
a9.reshape(3, 5, 1)

array([[[4],
        [1],
        [3],
        [6],
        [7]],

       [[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]]])

In [32]:
a9.T

array([[4, 2, 3],
       [1, 0, 1],
       [3, 3, 5],
       [6, 1, 5],
       [7, 7, 9]])

In [33]:
a13 = np.random.randint(10, size=(3, 3))
a14 = np.random.randint(10, size=(3, 2))
a13, a14

(array([[3, 5, 1],
        [9, 1, 9],
        [3, 7, 6]]),
 array([[8, 7],
        [4, 1],
        [4, 7]]))

In [34]:
np.dot(a13, a14)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [35]:
a15 = np.random.randint(10, size=(4, 3))
a16 = np.random.randint(10, size=(4, 3))
a15, a16

(array([[9, 8, 8],
        [0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[0, 7, 2],
        [2, 0, 4],
        [9, 6, 9],
        [8, 6, 8]]))

In [36]:
np.dot(a15, a16)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [37]:
np.dot(a15.T, a16)

array([[128, 153, 146],
       [135, 140, 167],
       [ 28,  68,  56]])

In [38]:
a17 = np.random.randint(10, size=(4, 3))
a18 = np.random.randint(10, size=(4, 3))
a17, a18

(array([[7, 1, 0],
        [6, 6, 7],
        [4, 2, 7],
        [5, 2, 0]]),
 array([[2, 4, 2],
        [0, 4, 9],
        [6, 6, 8],
        [9, 9, 2]]))

In [39]:
a17 > a18

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [40]:
a17 >= a18

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [41]:
a18 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True,  True, False]])

In [42]:
a17 == a18

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
np.sort(a17)

array([[0, 1, 7],
       [6, 6, 7],
       [2, 4, 7],
       [0, 2, 5]])

In [44]:
np.argsort(a17)

array([[2, 1, 0],
       [0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [45]:
np.argmax(a17)

0

In [46]:
np.argmin(a17)

2

In [47]:
np.argmax(a17, axis=1)

array([0, 2, 2, 0], dtype=int64)

In [48]:
np.argmax(a17, axis=0)

array([0, 1, 1], dtype=int64)

In [49]:
np.random.randn(3, 2)

array([[ 0.08704707, -0.29900735],
       [ 0.09176078, -1.98756891],
       [-0.21967189,  0.35711257]])

In [50]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])